### ISSUE TITLE
autoIndex does not list files and folders by default in windows 10 

### ISSUE THREAD

**Issue by RobertWu-TIBCO** [http-party/http-server#543] opened 2019-07-11 08:40 UTC
**Do you want to request a *feature* or report a *bug*?**
A bug maybe ?

**If the issue is a bug report, please provide the steps to reproduce it. Please include the actual command causing the issue if applicable.**

npm install http-server -g
open "http://127.0.0.1:9998"

**What did you expect to happen?**
Since `-i Display autoIndex (defaults to true)`, I should expect the url to list all my files and folders.

**What actually happened? Please include the actual error trace and / or stack trace if applicable.**
But instead it shows `ERR_INVALID_REDIRECT`.

[Thu Jul 11 2019 16:35:51 GMT+0800 (GMT+08:00)] "GET /" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36"

**If the issue is a feature request, what is the motivation / use case for it?**

**Tell us about your environment**
- **http-server version:**
- **Platform:**
win 10 Enterprise G  X64 , npm  version 6.1.0 , run in mobaxterm

**Other information (related issues, suggestions for a fix, etc):**

**Comment by bjornharrtell** [comment] 2019-08-07 14:22
This is actually a regression in a dependency, see https://github.com/jfhbrook/node-ecstatic/issues/260, with little hope of getting fixed.

**Comment by thornjad** [comment] 2019-08-20 19:54
Duplicate of #525

**Closed by thornjad** 2019-08-20 19:54 UTC
