### ISSUE TITLE
Server not providing paths with . (example www.test.com/.well-know/ssl/data.txt)

### ISSUE THREAD

**Issue by tekbird** [http-party/http-server#441] opened 2018-04-12 20:44 UTC
How to allow the server to resolve local path in which a directory name starts with dot.

**Comment by BigBlueHat** [comment] 2018-04-12 20:51
`.` prefixed files and folders are typically hidden (by design) on filesystems, so whatever we used to enable them will need to take that into account.

**Comment by tekbird** [comment] 2018-04-12 20:53
In linux, is there any way to do it?

**Comment by BigBlueHat** [comment] 2018-04-13 15:11
First, we'd need tests for the `.well-known` scenario as well as tests against other likely-to-be-present` folders (or files) like `.git/` and `.gitignore`. Once we have those we can determine if it's http-server or [node-ecstatic](https://github.com/jfhbrook/node-ecstatic) that need the fix.

**Comment by thornjad** [comment] 2019-12-20 14:21
This @tekbird would you please confirm if this issue is still present in the latest version of http-server? It looks like I'm able to serve dot-directories without an issue.

**Comment by thornjad** [comment] 2020-02-10 16:42
Closing under the assumption this is now fixed, please reopen if this is not the case

**Closed by thornjad** 2020-02-10 16:42 UTC
Labels: please-confirm
