### ISSUE TITLE
The routing cannot be found on the refresh page

### ISSUE THREAD

**Issue by zhoulihan** [http-party/http-server#376] opened 2017-06-21 03:04 UTC
Refresh the page will not find the routing, it is recommended to add a try_files, may be resolved

**Comment by BigBlueHat** [comment] 2017-06-21 12:15
Thanks for reporting this issue. Did this happen when changing files in the directory? Were there any symlinks involved?

**Comment by yamishav** [comment] 2018-01-02 05:35
+1

**Comment by xucito** [comment] 2018-02-21 05:23
+1 - Occurs for me when I refresh a page that is not the root. Need to redirect to Index.html as it cannot find the path in the directory.

**Comment by ThunderRoid** [comment] 2018-06-28 06:41
Same here, any fix yet or update on this?

**Comment by thornjad** [comment] 2019-12-20 14:13
I'm not sure I understand what the issue is here. Are you getting a 404 error when refreshing pages?

**Comment by thornjad** [comment] 2019-12-20 15:19
After some more searching, I believe this is a duplicate of #519

**Closed by thornjad** 2019-12-20 15:19 UTC
Labels: needs-more
