### ISSUE TITLE
Allow use of config file instead of command line params

### ISSUE THREAD

**Issue by JEAxero** [http-party/http-server#696] opened 2021-07-12 17:37 UTC
I'm getting started using http-server and would like to be able to put my command line params in a config file and have that used instead.

For example: http-server --config my_config.json

where my_config.json would have something like this:

{ port: 8484, gzip: true, brotli: true, proxy: "http:localhost:8484?" }

Which would run as if I typed this at the command line:

http-server ./dist --port 8484 --gzip --brotli --proxy http://localhost:8484?

**Comment by thornjad** [comment] 2021-07-12 19:34
I'm generally in favor of this, though this is a duplicate of #24 (one of our oldest issues). It did have a PR (#131) attached but it couldn't keep up with changes in `master`. I'd welcome a new PR for sure.

**Closed by thornjad** 2021-07-12 19:34 UTC
