### ISSUE TITLE
Http to https redirect

### ISSUE THREAD

**Issue by catherineVoo** [http-party/http-server#765] opened 2021-11-17 08:00 UTC
Hello,

Having a positive result in Lighthouse (devtools) PWA testing is currently not possible anymore: Lighthouse requests a http > https redirection to give a positive audit. A nice to have feature would be a simple option added when we start the server (like "--redirect-https" for example).

**Comment by thisIsTheFoxe** [comment] 2021-12-04 19:10
Possible duplicate of:
- #273 
- #598
- #600

**Comment by thornjad** [comment] 2021-12-06 20:52
Yeah I'm going to call this a duplicate of #273

**Closed by thornjad** 2021-12-06 20:52 UTC

**Comment by catherineVoo** [comment] 2021-12-07 07:54
Thank you for the info. Maybe it's a good idea to add the info in the documentation ?
