### ISSUE TITLE
Unable to load the page on windows 10

### ISSUE THREAD

**Issue by harshan89** [http-party/http-server#534] opened 2019-05-30 13:12 UTC
**Unable to load the page on windows 10**

The site at http://127.0.0.1:8080/ has experienced a network protocol violation that cannot be repaired.

I have stop firewall.

**Environment**
- **http-server version:** 0.11.1
- **Platform:** Windows 10

**Other information**

![Capture](https://user-images.githubusercontent.com/9652826/58634875-03500c00-830a-11e9-8d75-dd4be455df76.PNG)

but server is up and running

![Capture](https://user-images.githubusercontent.com/9652826/58635297-27f8b380-830b-11e9-93b0-6cfe246f7692.PNG)

**Comment by adibikar** [comment] 2019-05-31 02:46
Me too. Both chrome and mozilla shows error. On windows 7 with latest version of browsers.

**Comment by harshan89** [comment] 2019-05-31 05:09
> Me too. Both chrome and mozilla shows error. On windows 7 with latest version of browsers.

Here also with latest version of browsers.

**Comment by wojciechfornal** [comment] 2019-06-06 06:41
Same here after upgrading to the latest node and fetching http-server again (ecstatic bumped from 3.3.1 to 3.3.2). A bunch of response headers missing, one of which is "Content-Type".

Reverted back to previous node and http-server (ecstatic-3.3.1) and all works fine again,

**Comment by imfaber** [comment] 2019-06-09 08:52
Same here. It would seem the options `-d` and `-i` don't work. 
If I add `index.html` to the URL it's fine.

For the moment I downgraded to `0.9.0` which seems to work

**Comment by sok0** [comment] 2019-06-09 15:17
Same problem

![image](https://user-images.githubusercontent.com/39022834/59160792-f7451680-8a8e-11e9-9072-2ce16465824f.png)

**Comment by Cristuker** [comment] 2019-06-13 02:02
Me too

**Comment by Cristuker** [comment] 2019-06-13 22:13
It worked

> 
> 
> Same here. It would seem the options `-d` and `-i` don't work.
> If I add `index.html` to the URL it's fine.
> 
> For the moment I downgraded to `0.9.0` which seems to work

**Comment by HighTechnocrat** [comment] 2019-06-19 20:20
I'm having the same issue in 0.11.1 on Windows 10 in both Chrome and Firefox.

```
./node_modules/.bin/http-server -g -o
```

Navigating directly to ./index.html works, but the index file is not being loaded by default

**Comment by rbirkgit** [comment] 2019-06-24 16:59
I just spent two hours on this before realizing you have to include /index.html in the URL. Is there no way to add default page as a parameter?

**Comment by guerrillacontra** [comment] 2019-07-05 11:18
I also have the same issue, same error.

**Comment by davidboy** [comment] 2019-07-19 16:47
Same issue here

**Comment by zipzit** [comment] 2019-07-21 19:14
Same issue?  I'm testing out my single page application, with # redirects... and the redirects keep pointing to http://127.0.0.1:8080#menuX and not http://127.0.0.1:8080/index.html#menuX, etc...     

I tried a proxy fix `http-server --proxy http://127.0.0.1:8080/index.html?` but that didn't seem to work.

Windows 10, version 1903 (OS Build 18362.239)
http-server@0.11.1

**Comment by lcousino** [comment] 2019-07-28 21:54
Someone advised me to try installing live-server (npm install -g live-server), then run live-server from the terminal, it worked for what I was trying to do. Hope this helps.

**Comment by AzyCrw4282** [comment] 2019-08-18 23:30
Came across the same error and by simply doing this 'http://127.0.0.1:8080/index.html' I was able to get it working.

**Comment by thornjad** [comment] 2019-08-19 15:57
Duplicate of #525

**Closed by thornjad** 2019-08-19 15:57 UTC
