### ISSUE TITLE
OPTIONS Requests Crash App

### ISSUE THREAD

**Issue by drumrz** [http-party/http-server#671] opened 2021-01-08 22:08 UTC
**Steps to reproduce the issue, if applicable. Include the actual command and output and/or stack trace.**

curl -i -X OPTIONS http://example.org/path
  OR
curl -i --request-target "*" -X OPTIONS http://example.org

**What did you expect to happen?**

Webserver should not crash.

Output in the log looks like this, and it grows and grows until the app crashes.

[Fri Jan 08 2021 14:24:20 GMT-0500 (Eastern Standard Time)] "OPTIONS /" "curl/7.60.0"
[Fri Jan 08 2021 14:24:20 GMT-0500 (Eastern Standard Time)] "OPTIONS /?/" "curl/7.60.0"
[Fri Jan 08 2021 14:24:20 GMT-0500 (Eastern Standard Time)] "OPTIONS /?/?/" "curl/7.60.0"
[Fri Jan 08 2021 14:24:20 GMT-0500 (Eastern Standard Time)] "OPTIONS /?/?/?/" "curl/7.60.0"
[Fri Jan 08 2021 14:24:20 GMT-0500 (Eastern Standard Time)] "OPTIONS /?/?/?/?/" "curl/7.60.0"
[Fri Jan 08 2021 14:24:20 GMT-0500 (Eastern Standard Time)] "OPTIONS /?/?/?/?/?/" "curl/7.60.0"
[Fri Jan 08 2021 14:24:20 GMT-0500 (Eastern Standard Time)] "OPTIONS /?/?/?/?/?/?/" "curl/7.60.0"
[Fri Jan 08 2021 14:24:20 GMT-0500 (Eastern Standard Time)] "OPTIONS /?/?/?/?/?/?/?/" "curl/7.60.0"
[Fri Jan 08 2021 14:24:20 GMT-0500 (Eastern Standard Time)] "OPTIONS /?/?/?/?/?/?/?/?/" "curl/7.60.0"
[Fri Jan 08 2021 14:24:20 GMT-0500 (Eastern Standard Time)] "OPTIONS /?/?/?/?/?/?/?/?/?/" "curl/7.60.0"
[Fri Jan 08 2021 14:24:20 GMT-0500 (Eastern Standard Time)] "OPTIONS /?/?/?/?/?/?/?/?/?/?/" "curl/7.60.0"
[Fri Jan 08 2021 14:24:20 GMT-0500 (Eastern Standard Time)] "OPTIONS /?/?/?/?/?/?/?/?/?/?/?/" "curl/7.60.0"
[Fri Jan 08 2021 14:24:20 GMT-0500 (Eastern Standard Time)] "OPTIONS /?/?/?/?/?/?/?/?/?/?/?/?/" "curl/7.60.0"
[Fri Jan 08 2021 14:24:20 GMT-0500 (Eastern Standard Time)] "OPTIONS /?/?/?/?/?/?/?/?/?/?/?/?/?/" "curl/7.60.0"

**If the issue is a feature request, what is the motivation / use case for it?**

**Tell us about your environment**
- **exact http-server version:**

├─┬ http-server@0.11.1
│ ├── colors@1.0.3
│ ├── corser@2.0.1
│ ├─┬ ecstatic@3.3.0
│ │ ├── he@1.2.0
│ │ ├── mime@1.6.0
│ │ ├── minimist@1.2.0
│ │ └── url-join@2.0.5
│ ├─┬ http-proxy@1.17.0
│ │ ├── eventemitter3@3.1.0
│ │ ├─┬ follow-redirects@1.6.1
│ │ │ └─┬ debug@3.1.0
│ │ │   └── ms@2.0.0 deduped
│ │ └── requires-port@1.0.0
│ ├── opener@1.4.3
│ ├─┬ optimist@0.6.1
│ │ ├── minimist@0.0.10
│ │ └── wordwrap@0.0.3
│ ├─┬ portfinder@1.0.20
│ │ ├── async@1.5.2
│ │ ├─┬ debug@2.6.9
│ │ │ └── ms@2.0.0
│ │ └─┬ mkdirp@0.5.1
│ │   └── minimist@0.0.8
│ └─┬ union@0.4.6
│   └── qs@2.3.3

- **Node version:**
v10.23.0

- **Platform:**
Red Hat Enterprise Linux Server release 7.9 (Maipo)

**Comment by thornjad** [comment] 2021-07-06 22:50
This is interesting, we've had issues with a redirect loop like this on Windows, but I'm surprised to see it in Linux. There's a chance this could be fixed by #693, so I'm going to wait to investigate until that's merged

**Comment by thornjad** [comment] 2021-08-17 14:01
I've been unable to reproduce this, is anyone seeing this same issue with http-server v13.0.0?

**Comment by thornjad** [comment] 2021-10-06 18:59
I'm going to assume this is fixed in v13 because its similar to other issues which were fixed, please reopen if this is not the case

**Closed by thornjad** 2021-10-06 18:59 UTC
