### ISSUE TITLE
http-server on localhost:8080 isn’t working

### ISSUE THREAD

**Issue by muiloo1998** [http-party/http-server#554] opened 2019-08-16 17:58 UTC
When I run this `node bin/http-server` command, I am getting following error message.

> This page isn’t working localhost sent an invalid response. ERR_INVALID_REDIRECT

**Environment**
- **http-server version:** 0.11.1
- **Platform:** Windows 10

What would be a solution?

**Comment by thornjad** [comment] 2019-08-18 03:23
Duplicate of #525

**Closed by thornjad** 2019-08-18 03:23 UTC
