### ISSUE TITLE
Why is .js.gz file not being served?

### ISSUE THREAD

**Issue by RichardJECooke** [http-party/http-server#300] opened 2016-08-18 08:54 UTC
I gzipped my `app.js` to `app.js.gz` and then ran `http-server -g`, as specified in the readme of this website.

But my browser still receives the .js file, not the .js.gz file, as you can see in the screenshot. Is this is a bug?

![untitled](https://cloud.githubusercontent.com/assets/5468805/17767885/2199e47c-6532-11e6-9b23-702dec72be1f.png)

**Comment by RichardJECooke** [comment] 2016-08-18 10:00
Update: If I change my index.html to request app.js.gz directly it all works. But I thought the whole point of gzipping is that it's done invisibly - your browser can request a normal .js file and secretly receive the .gz one

**Comment by derhuerst** [comment] 2016-08-18 10:36
In chrome dev tools, check the "Transferred" column or the `Content-Encoding` for a single request.

Only because you see `app.js`, that doesn't mean it has been transferred uncompressed.

**Comment by RichardJECooke** [comment] 2016-08-18 10:39
If I delete the .js file, so http-server is forced to server the .js.gz file, I get a browser error.  So it's definitely not working.

**Comment by derhuerst** [comment] 2016-08-18 10:42
That's also not how transparent gzipping works. Usually, the server gzips on-the-fly, so the url points to the ungzipped file.

I will have a look in a minute.

**Comment by derhuerst** [comment] 2016-08-18 10:44
[`lib/http-server.js` looks like you have to pass `gzip: true`](https://github.com/indexzero/http-server/blob/fed98f2dbb87f1ea7a793e48a1975c20c9e970fa/lib/http-server.js#L49). Have you done that?

**Comment by RichardJECooke** [comment] 2016-08-18 10:48
Yeah, my understanding is that it should gzip on the fly too - I'm used to how IIS works. But the documentation on this site says using `-g` will server a .js.gz file if it exists, implying you have to create it yourself.

So now I tried deleting my manually created .gz file to see if maybe http-server zips it automatically. But it doesn't:
![untitled](https://cloud.githubusercontent.com/assets/5468805/17771131/d3d26ace-6541-11e6-90f6-b5717c618fc1.png)

**Comment by RichardJECooke** [comment] 2016-08-18 10:48
I don't know what you mean by `pass gzip: true`.  I'm running `http-server -g`

**Comment by derhuerst** [comment] 2016-08-18 10:50
I agree that it should gzip on `http-server --gzip`. I was referring to the usage from Node.js, this is the command line equivalent.

Regarding your screenshot: It's not about `Content-Type`, it's about `Content-Encoding`. But that is missing as well.

I will check on my computer in a few minutes.

**Comment by derhuerst** [comment] 2016-08-18 11:00
The `gzip` option has been introduced in b456b77, which has not been published to npm yet. You can check by running `npm info http-server@latest gitHead`.

You will have to wait until this is published or use `http-server@indexzero/http-server` (Git dependency).

**Comment by intellix** [comment] 2016-11-28 00:23
damnit, was also wondering why my gzip wasn't working after looking at the code :(

**Comment by cgatian** [comment] 2017-01-30 21:30
Sadly, this is not in the 0.9.0 release.

**Comment by the0neWhoKnocks** [comment] 2017-10-31 21:18
I'm running `0.10.0`, looks like the gzip PR's in there, but I'm still not seeing gzipped content come through. I'm running `http-server ./build --gzip -o -p 8080`.

After reading through `ecstatic`'s docs, https://www.npmjs.com/package/ecstatic#optsgzip led me to what @RichardJECooke tried (to manually create a `.gz` file). After doing so, I'm seeing that file served. 

The confusion seems to come from the fact that most servers that have a "simple setup" (and gzip is one of the available options), the server will do the work of gzipping for you (which is what I expected). This should really be called out in the docs to lessen confusion.

Possible solutions to anyone that come across this issue:
- Ask the `ecstatic` folks to update the `middleware` function to utilize the built in `zlib` module so files get automagically served up gzipped.
- If you're utilizing WebPack to build out assets, you can use the `CompressionPlugin` to generate the `.gz` files at build time with a configuration like this
```
new CompressionPlugin({
  asset: '[path].gz[query]',
  algorithm: 'gzip',
  test: /\.js$|\.css$|\.html$/
})
```

**Comment by BigBlueHat** [comment] 2017-11-01 13:25
@the0neWhoKnocks I definitely agree we need to make this clearer in the docs. I'm not sure, though, that we should add any compression magic to the code--as it goes a bit against the whole static server thing. It would be good to have more docs and tests around this bit, so it's more obvious how it works and what steps one needs to take to use it.

**Comment by the0neWhoKnocks** [comment] 2017-11-01 14:16
@BigBlueHat Agreed. Calling out that this module is a `static` server would be good to add to the README as well. There's not one mention of that there.

**Comment by thescientist13** [comment] 2018-07-08 02:58
Running `0.11.0` and can confirm `gzip` now works as expected (I'm generating my own `*.gz` files with **webpack**

Thanks for all the good work!  ✌️

**Comment by BigBlueHat** [comment] 2018-07-09 14:06
Great to hear @thescientist13!

I'd love some tests for this added, so we can be sure to avoid regressions. I'll leave this open for anyone interested in sending a PR to improve the tests and/or README.

**Comment by the0neWhoKnocks** [comment] 2018-07-10 13:42
@thescientist13 as I stated above, it worked if you generated your own `gz` files. The issue I was having was that if I enabled/passed a flag saying "turn gzip on", I was expecting the server to do the gzip'ing on the fly. I'm fine with generating the files manually (now that I know that's what I was supposed to do). It was just frustrating at the time since I wasted time thinking it was user error. Really what the `--gzip` flag does, is say "if a gz version of a file exists, I'll use that instead" - not "I'll now gzip and serve specified file types".

**Comment by thornjad** [comment] 2019-12-20 14:10
The gzip option in the README now specifies that it looks for an existing file. Since there are plenty of tests in ecstatic around gzip (and brotli), I'm going to consider this done.

**Closed by thornjad** 2019-12-20 14:10 UTC
Labels: faq, feature:documentation, feature:mime

**Comment by Nashorn** [comment] 2020-09-29 11:14
This does not work at all. .gz file created, -g and --gizp flag usdD. Only the .js loads.
Altering <script> tag ref to .gz file, loads but won't decompress. 

This thread needs reopening

**Comment by cgatian** [comment] 2020-09-29 11:33
Use [server](https://www.npmjs.com/package/server). Way better as it serves gzip by default. Maintainers listen to feedback.

**Comment by thornjad** [comment] 2020-10-12 14:55
@Nashorn What is the `content-encoding` response header for that file?

**Comment by musema** [comment] 2021-02-19 10:08
> This does not work at all. .gz file created, -g and --gizp flag usdD. Only the .js loads.
> Altering <script> tag ref to .gz file, loads but won't decompress.
> 
> This thread needs reopening

were you able to fix providing gzip content to <script> tag?

**Comment by rgr-t** [comment] 2026-02-28 03:28
2026 still not working
