### ISSUE TITLE
i want change the default file for directory request, not index.html

### ISSUE THREAD

**Issue by hisland** [http-party/http-server#754] opened 2021-10-19 01:25 UTC
#### What's the problem this feature will solve?

i want change the default file for directory request, not `index.html`

#### Describe the solution you'd like

give me an option to set the file name

#### Alternative Solutions

or i can disable the feature, just list the files in my directory

**Comment by chris--jones** [comment] 2021-10-19 02:43
Duplicate of #678, I've started a fix here which just requires some more testing / unit tests: https://github.com/chris--jones/http-server/tree/index-and-notfound

**Closed as completed** 2021-10-19 16:54 UTC

**Comment by fitcwill** [comment] 2022-07-26 04:02
Catching up on this. Says closed as completed which was misleading at first. Is it not possible to close as duplicate?
