### ISSUE TITLE
wasm does not need charset and does not work on firefox chrome

### ISSUE THREAD

**Issue by frank-dspeed** [http-party/http-server#618] opened 2020-03-27 16:21 UTC
https://www.youtube.com/watch?v=n6hIa-fPx0M&t=618s

whole google episode about your server :)

**Comment by thornjad** [comment] 2020-04-06 15:20
Huh, that's pretty cool. Thanks for linking that, I'll take that as authority that wasm shouldn't have charset!

**Comment by frank-dspeed** [comment] 2020-04-06 16:35
@thornjad in general every binary file does not have a charset. charset is for text file formats.

**Comment by thornjad** [comment] 2020-04-27 17:28
Finally had some time to investigate this, and this is actually coming from a dependency, `ecstatic`. I'm currently working on removing that dependency, and will be able to fix this after that.

**Comment by frank-dspeed** [comment] 2020-04-28 05:12
@thornjad you should consider express static as a replacement that is maintained.

**Comment by RobLoach** [comment] 2020-05-24 18:43
I've switched to [local-web-server](https://github.com/lwsjs/local-web-server).

``` bash
npm i local-web-server --global
ws
```

**Comment by frank-dspeed** [comment] 2020-05-25 08:14
@RobLoach 
https://open-wc.org/developing/es-dev-server.html
```
npm i --save-dev es-dev-server
```

**Comment by phi-fell** [comment] 2020-09-17 08:05
for people (like me) looking for a drop in replacement for this that serves wasm files correctly, but also handles extensions nicely (as this does), `npx serve` is a fine replacement, as is `npx local-web-server` (theres a commandline option for setting default extension).  these both fit all the needs I had for `http-server`, before I started needing to serve wasm, and they seem to serve wasm files with the correct content type.

`es-dev-server` will give a 404 if you omit the `.html` in file names (which differs from http-server and there does not appear to be a commandline arg to change it) and is also *very* slow.  I don't know what it's doing but it takes a solid several seconds to quit after a ctrl-c (or multiple) and is just generally slow to use.

**Comment by thornjad** [comment] 2021-07-06 22:38
Duplicate of #480

**Closed by thornjad** 2021-07-06 22:39 UTC
Labels: ecstatic, feature:mime, minor
