### ISSUE TITLE
EADDRINUSE 0.0.0.0:8086 error for multiple instances

### ISSUE THREAD

**Issue by shershen08** [http-party/http-server#325] opened 2016-11-02 12:44 UTC
Recently started having following error when trying to start more than one instance of whs.
```
Error: listen EADDRINUSE 0.0.0.0:8086
    at Object.exports._errnoException (util.js:1036:11)
...
```
whs version - 3.10.9
node version v6.6.0

console output looks like this

```
$ whs -p 4444
Websocket Server Listening on Port: 8086
Starting up http-server, serving ./ on: http://127.0.0.1:4444
Hit CTRL-C to stop the server
events.js:160
      throw er; // Unhandled 'error' event
```

**Comment by BigBlueHat** [comment] 2017-05-02 14:35
As of `0.10.0` if you've *not* specified a specific port via the `-p` option, then one will be auto-selected for you by `portfinder` (now upgraded to `1.0.13`.

That said, the example you've listed specifies port (via `-p 4444`), so that would still throw that error.

However, we're discussing a `--find-port` option in #363 and your input there would be welcome!

**Comment by thornjad** [comment] 2019-12-18 15:25
Comments are welcome in #363, but for now I'm going to close this since a) the latest versions of http-server should find a new port by default, and b) it is intended behavior that trying to run multiple instances on the same port is an error.

**Closed by thornjad** 2019-12-18 15:25 UTC
