### ISSUE TITLE
-a is not working

### ISSUE THREAD

**Issue by jorwong** [http-party/http-server#709] opened 2021-07-27 06:16 UTC
**Steps to reproduce the issue, if applicable. Include the actual command and output and/or stack trace.**

http-server index.html -a 0.0.0.0 -p 8080

**What did you expect to happen?**
Running this command should open up 0.0.0.0:8080. However, it reverted back to using localhost instead.

Starting up http-server, serving index.html
Available on:
  http://127.0.0.1:8080
  http://172.18.0.2:8080

**If the issue is a feature request, what is the motivation / use case for it?**

**Tell us about your environment**
- **exact http-server version:** v0.12.3
- **Node version:** v10.19.0
- **Platform:** Ubuntu

**Other information (related issues, suggestions for a fix, etc):**

**Comment by thornjad** [comment] 2021-08-07 17:57
Duplicate of #615, this is fixed on `master` but not yet released

**Closed by thornjad** 2021-08-07 17:57 UTC

**Comment by timjrobinson** [comment] 2021-09-28 00:43
@thornjad It's broken on master too right now, looks like there was a regression. I cloned this repository, ran npm install and then:

```
> node bin/http-server -a 0.0.0.0           
Starting up http-server, serving ./public

http-server settings:
CORS: disabled
Cache: 3600 seconds
Connection Timeout: 120 seconds
Directory Listings: visible
AutoIndex: visible
Serve GZIP Files: false
Serve Brotli Files: false
Default File Extension: none

Available on:
  http://127.0.0.1:8080
  http://192.168.50.133:8080
Hit CTRL-C to stop the server
```

**Comment by timjrobinson** [comment] 2021-09-28 01:06
Ah I see it's still opening on 0.0.0.0 but the available on says 127.0.0.1 from the change in https://github.com/http-party/http-server/pull/728. Why did you make it show a different IP in the output?

**Comment by thornjad** [comment] 2021-09-28 01:18
We could add in both to be more correct, it was a side effect of `-o` not working properly on windows with 0.0.0.0.

**Comment by thornjad** [comment] 2021-09-28 01:19
You could open a new issue to show the 0.0.0.0 when it's used. I'm not sure if there's a good way to detect whether it's available on localhost or not, though
