### ISSUE TITLE
`Available on:` text without right hand side, where are files being served?

### ISSUE THREAD

**Issue by dvtate** [http-party/http-server#815] opened 2022-05-25 19:22 UTC
#### Environment Versions

1. Linux (Arch)
1. Node version: 18.2.0
1. http-server version: v14.1.0

#### Steps to reproduce

run `http-server`

#### Expected result

I expect it to tell me where the files are being served

#### Actual result

It does not share this information

```
> http-server .

Starting up http-server, serving .

http-server version: 14.1.0

http-server settings: 
CORS: disabled
Cache: 3600 seconds
Connection Timeout: 120 seconds
Directory Listings: visible
AutoIndex: visible
Serve GZIP Files: false
Serve Brotli Files: false
Default File Extension: none

Available on:
Hit CTRL-C to stop the server
```
Notice the second to last line in the above text copy-pasted from my terminal.

**Comment by zbynek** [comment] 2022-05-29 20:21
This is duplicate of #810

**Closed** 2022-05-29 22:52 UTC
