### ISSUE TITLE
Seeing matrix style ASCII response when running http-server

### ISSUE THREAD

**Issue by max-segale** [http-party/http-server#788] opened 2022-01-10 17:43 UTC
I am trying to run a local http server and I get a strange response.

This started happening the morning of 2022-01-10

#### Environment Versions

1. MacOS 12.1
1. Node version: v14.17.3
1. http-server version: 14.0.0

#### Steps to reproduce

`npx http-server`

#### Actual result

```
t̸̛̳̥̜̭̰͓̖̹̟͓̝̳̭̳̦͓̼̦̼͔̹͇̬͈̖̤͙̯̘̟̮̹͙̘̩͙̜̪͚̳̳̥͎̻̞̪̔͑͑̾ͧͦ̏ͭ̕͝ͅę̵̝̖͎͓̼̖͖͓͖̭̫͉͇̜̞̺͉̼̣̼͎͙̦̬͊̈͐ͭ̽͢͜͝ͅs̶͚̝̳̣̗̝̘̰̙͕͕̪̺̙̣̘̪͔̦̦͇͇̯̪̤̤̟̱͓̗̘͎̯͇̻̮̰̯̩̦͍͖̪̮̙̹̪̻͚̱̥̥̪͉͉̦͇̳̞͓̑ͨͨͣ̌́͡t̷̯̪̪͖̜̻̜̠̖̫̯͇͈͔͓͚͉͔̜̦̞͈̝͚̥͒̈ͯ̆ͮ͋̽̑̔̾ͤ̐̚͢͝ï̇̌̈͂͛̚ ҉̸̸̴̥̰̥͇͖̝̰̗͖̼̲̙̗̯̫̮̥̦̼̩͍͈͉̼̗̝̭̟̼͖͕̼̠̣̫͍͎̟͇̰̘̺̯̰̯̰̦̰̲̞̫̻̀ͅͅͅnͧ̂̆͂̅ͣ̾̆̈ͮͮͣ̊ͫ̐̓͌̕ ҉̲̮̘͚̠̻̱̻͖͓͇͖̯̞̘̜̯g̷̨̜̖̰̰̤̠͍̭̻̦̘̦̲̲͙̲̼͛̈ͣ͆̇͑ͣ̊̄̚͢͟͠ ̸̢̓͗̎̈̾ͦ̃̉̈̑ͤͤ͆͂͐͛̽̄́ ҉̣͎͎̜̳̪̭͎̻͍̭̼͈͙͈͓͎̜̜̺̯ṯ̡̥̺͔̠̞̹͈̜̦̝̞̖͓͍̠̫̠̝̬͔͖̜̘̗͖͇͈̗̠͚̺͕͎̼̳̫̞̘̪͎̲̤̀ͫ̒̾͒̋̀̍̓̒̔ͯͯͯ̋̿̊̕͜͢͝ȩ̷̵̦̺̥̤̱̺̟̠̠̠̺̘̜͔͍͚̤̙͓̦̝̣̱̯̘̠͙̫͍̰̳̱͉͛ͨ̃́̾͟ͅs͎̳̲̮̟̩̱̦̳͎̉͑ͮ̒̔̈͌̑̐ͮ͊ͣ̉͛͒́̀̕͟͢ͅt̨͇̬͎̟͇̗͔̥̯͇̥̳͇̙̻͔̰̮̞͚̝͎͙̲̪̯͈̝̥̫̮̫̮̭͇̺̦̜̼̺̫̞̪̠͚̥̞͎͕͎̻̙͇̖̱̤̼̮ͨͤ̇̑̐ͪͨ̆͌̓ͤ̂ͮͫ̓ͬ̽͠ͅͅi̡̧͈̗͍͈̥̣̞̯̳ͩ̅ͨ̆̎͘͞n̨͈̻͎̦͕̯̩̠̙͓͇͇̖͉̺̲̖͙͔̜̥̞̠͓̩͈̹̳̰̗̣̟̫͇̣̪͖͕͙̬͉͍̮̍̆̏̃ͤ̔ͣͯ̇ͦ̋ͪ̉̋ͭ̊ͧ͡͞ͅͅg̷̤͔̭̬̱̫̼͎̭̼̭̪̙͖͕̟̱̫̪̩̼̘̠͕͔̦͙͉̯̥̗̘̪̼̻̟͈̭̪̬̹͍̝͎̯̤̤͓͙̭̤̺̭ͫͨ̃̍͞ͅ ̴̧͕̞͚̤͇͍̻̼̺̩̜̱̺̠̝͔͕̽̌̂ͮţ̴̡̣̭̘̞͕͓̮̞̱̣̪̫̹̪͖̰͇̮͓͉̗̜̥̬̪̹͕̼͇̗̭͔͉̦͎̱͉͓̤̠̫̤̖͕̪̭͕̠̬̼ͩͩ̿̇̕͠ͅe̛̫̖̠͕̝͍̭̖̝̰̬͈̫̙͕̜͙͉̞̻̤̺̣͚͖̣̲̬͍̟̘͎̯̞͈͎̺̱̠̱̞̞͎͚̥͈̘̲̫̙͓ͦ̈̅͒͊̀͛ͣ͐͞ͅs̪̫̰͕̟̺̱̟̪͇̥͈̻̠̱̟͍͇̯͎͔̻͓͈̩͔̩̗̗̩͇̜̜̦̰̞̝̜̗̼̳̣̩̲͈͙͎̹̯̬̮̰̟̠̝̮̖̖̠͈̀͌ͧ̽̓ͧ̅ͪͬ̃̈͒̏̀ͭ͘͜ͅͅt̴̶̬̣̪̱̻̫͖̖͉̞̬̳̹̞̉͐͊̚̚͜͢i̢̧͈̗̻͇̰̮̻̖̖̜͍̲̪͈̲̹̗͖͚͕̞̤̖͉̭̺̟̳̫͇̺̫̬͖̣̣̮̼̬̞͍̟̞͈̠͖̳̙̥̣͓̙͛ͣ̎ͬ͐ͦ͋ͪͮ̽̑̌͒͋͊̆̚͡ͅͅṋ̶̨̡̨͉̣̘̥̣͖͕̙̪̝̘̩̤̗͈̤͇̳̲͚̠̥͉͔̺̤̺̞̼̫̖̯̟̰̦͖̺̺̝͙̗͇̙̮̒ͯ͗̌̅̋̓͋̈ͮͫͭ̅̅̔͟ͅͅͅģ̥̺̣͎̖̺͚̭̙̜͈̼͇̭̪̬͉̼͓͙͇̙̻̝̲̝̞͉̳̼̣̰͓̫͚̹̯̮̰͎͇̱̻͇̣̼̹̩̖̭͚̪͖̼͚̹̬͙͓̒̄͑̏͂͆̂͛̀̂̈̃͆ͧ͐ͨ̆͆̕͞ͅ ̵̷̲͙̘̪̖̗̺̬̜̩̱̫͚̞̺̥̮̼̫̺͕̻̫̠̖̘̹͗̂̋̏̔̊ͪ̈̅ͫ͛̋͟͞͡ṫ̷̡̰͔̻̬̲̳͙̦̦̱̪̹͎̹̜̠̪̣̤̳̣̱̓̓ͯͬͨ͛̊̐̏ͭ̒̊̎ͤ̆ͫͤ̉͜͢ë̴̱̺̰̮̦̦̦̤̜̰͗ͦ͒̀s̨̬̪͍͉̳̪̺̻̯͇͚̜̞̠̺͍͕̥̲͖̖̺̳̰͉̲̗̙͎̦̜̭̪̗̳͓̤̫̜̹͎̲̤̩̹̠̻̯̳̺̯̗̻͙̠̟͉̯̗̹̗̭̙ͩ͊͛̄͟ͅͅt̴̛̑̿ͦ̊ͤ̊͒͊̆͂͟ ҉͕̰̼͍͖̫̗̘̭̯̯͙͉͈ͅͅi̶̵͚͚̝̣̯̻̬̱̪̦͔͉̟̱̼̜̖̭̼̬̩̦̪̭̐̉̔̒ͤͦ̏ͮ̀̅̈͡n̡̧̲̪̤̙̲̬̦̤̦̣̖̗̪̺̜̥̲̜̺̼̹͈͓̘̲̝̖͉͕̝͉̖̼̺͎̞̖͍̙̘̞̩̓͗ͩ̿́̊̆͂̌̏̀̈̐̌̏́̾ͯ͘͢g̅͂ͤ͌̇ͧͥ̉̾͛̅̓͟ ҉̰̟͔̗͉̦̫͔̫̞̩ ̸̴͙͕̘̭̳̞͉͍̰̣̫̻̗͍̣̮͎̫̖̮̟͇͓͙̣̱̣̞̙̫̝̟̲̣̠̭̟̄ͨ͌͌͗̎͑ͣͮͧ͒ͫͤͥ̇́́̚͡ͅt̷̹͎͕̖̩͌͐̉̃ͪ̈ͬ͋̿̑̃ͫ̇̕͠e̡̞̰̥͓̤͎̻̳̦̣̳̮̹̬̼͇̯̹͉̬̯̭̮͓̺͙̱̦̲̠̤̻͚̣̳ͫͭ̈̊͠s̥̠̘̫͈̦͖̜̖͖̹̦̥̭̫͕͚̪̘̻̣͚̱ͬ̑̃ͪ̑̑ͨ̆͢͡t͔̹̳̣͓̠͕̖̪̘̜̦͕̱̱̰͚͍̲̠̮̩̻̭̘̯̼̑ͩ̽ͤ̈͆̓ͥͫ͌̉̕͞͝i̷̸̴̧̛̜̩͇̼̲̹̭̳̬̘̜̣̣͛͊͌͛͂̓͊̈ͭͦ̉̽n̶̨̢̛̥̹̩̹̗͕͎̆̇́̋̋̏ͭ̉̈͘g̡̛̟̫̫̩̥̖̖͉̠͇̲̤̤̪͙̼͇̱͇̫̱̫̯̠̻̱̘̹̱̜̹̱͖̰̣̬͎̗̹̩̋ͯ̾̑͆͆̊ͮ̋̏͐͐̊̍͗̈͂͡ͅ ̢͙̫̮̲͖͍̪͉̤̖̟̘̗̜̹̠̺̙͕̝̩͎̻̪̜̙̭̪͙̗̤͎͈̬͉̮̲͖̭̩͕̩͉̬̳̤̩̟͍̥̺͖͇̺͖̫̻̯̯͂ͮ̔̆͌̔ͤ͑̏̿̄̇͋̕͟͜ͅͅt̷̨̼̼̹͙̮̤͕͓̞̗͍̻̺̫͚̲̤͕̲̮̰̥͇̲̬̱̫͉͎̥͎̜̥̩͓̘̱̝̘̫̼̙̲͚̺̮̺̬̱̫͚̟͔̼͎̟̰͕̼͑͗̌̾̓̍ͦͪͥͮͅe̝̼̳͚̲̖͔̱̝͍͉͕̘̪̳̖̱͉̺͙͖̘̞̥͕̲̭͔̗̲̭̼̼̮̠͍̣̮̜̹̤̩͕̫̱̞̭̩̙ͤ̒̑̄̋̒ͧ̈̋͐͌̏̈̓ͩ͢͜͜͠ͅͅs̵̶̢͎̩̪̘̳͙̰̯͚̫̮͔̲̤͙̫͍̟̥̜̖͍̘͔̲̹̭̭̹̖̣̠͓̻̯̱̘͔͓͔̝͔̫͉̠̹͕̳̲̦̠͇̞̥̺̃͂́ͨ̋̽ͨ͢͡ͅͅt̵̵͎̥͈̳͉̥̺͓̬̪̠̪̣̙̮͔͙̬̺̲̥̥̖̥̦̲͚̖̱̙̼̞͔̞̲̦̪̞̼̬̽ͣ̑̈̾̃̈̒͒͗ͪͤ̈̾̀i̵̼͉̠̬͚̜̝̳̣̻͊̈͛͋͑ͧ̿̇̑ͫ͛̇̃͊̀́̚͘͡n͒͆ͯ͌̅͛͗͂͊͒̎̉̐̃ ҉̶̬̦͈̙̣̯͎͖̩͓͇̱̝̲̞g̹̥͍̲̺̞̰͚͕̼͉̞̜͍̪̺̜͖͙͍̼͖͈̼̤͍̻̹̜̗̱̖͖̖̰̟̪ͭ̊̅͐̔͌̏̚̕͢ ̛̉̆̂̍͘͝ ҉̴̝̫̮̠̰̦̖͓͓͔̤̝̭͎̘̗͓̬̱̫̫ͅẗ̂ͣ͆̈̆̐̎̇̆ͣ̌̌̀̕ ҉̙̝̺͚̼͓̣͔̮̞̫͍͕̙̪̜̤̭͍͉̱̤͖̪͇̗̲̘̰̜̫̤̙͔͈̗̹̪̦̱̠̲͎̩́e̴͎͈̙̲͕̲͇͉͖̞̱̬̳̳̬̥͎͉̗͈̰͎̫̭̬̖͉͚̟͕͒ͣ̋̍ͨ̈́̋̎ͨ̇ͤ͑̃͜s̢ͭ̅̎͛̕͡͞ ҉͕̦̼͚̗̯͇̘̞͖̬͍̙̟ţ̢͎͉͓̟̼̺̗͍̩̹͍̤̻̮̦͚͚̯̯̘̞̣͙̺̩̘͚̼̰̱̏̈͑̌ͬ͗ͨ̉̓ͬ̈ͣ̓ͬ͘̕ͅͅͅi̴̵̥̰͙͈̯̰̞͙̖͔̲͚͓͓͖̜͈̫̜̖͚̟͓̗̘̪̰̼͕͓̳͙͓͔͎̞ͨͦ͊ͨ͊ͮ͜͜͠ͅͅͅņ̵̘̦̩͇̳̫͔̹̮̮̫̫͕̟̳̫̤̭̦͓̫͍̱̙̫͈̝͈̺̰̞̬͙̱̭̞͕̣̦̙̱̹̩͕̠ͯ̽̍̐͗ͫ̅ͩ̅́̏̚͟͠g̸̨̧͙͔̻͓͙̩̺̳̮̰̣̦͇̱͙̜̘̝̫͔̘͈̲̙̟̙̤̝͕͇̩̖͔̖̖̻̭̮̜̤̠̦͓͈͚̲͈̱̫̦̯͕͙͚̩̀ͥ̾ͤ̓ͥ̑̓̋̀͊̈̏̄̑ͣ̿͡͠ͅͅͅ

```

...

**Comment by nlucero** [comment] 2022-01-10 17:48
See #781

**Comment by thornjad** [comment] 2022-01-10 17:50
Yeah this is a whole dramatic dependency thing. It's not immediately obvious, but this is a duplicate of #781

**Closed by thornjad** 2022-01-10 17:50 UTC
