### ISSUE TITLE
Single Page App mode (404.html) - browser history not preserved

### ISSUE THREAD

**Issue by Jemt** [http-party/http-server#601] opened 2020-01-20 12:03 UTC
Http-server is a great application for local development. However, when working with a Single Page App, the approach using 404.html as the entry point has the disadvantage that the initial requests to any given URL is not stored in the browser history because the request returns a response with the HTTP status header set to _404 Not Found_ (tested with Chrome 79).

Please consider a flag allowing for a fallback path instead (probably relative to document root):
node_modules/http-server/bin/http-server root/ -c-1 -p8080 --fallback=index.html

**Comment by thornjad** [comment] 2020-01-29 14:09
Unfortunately http-server does not support SPAs, only pure HTTP content, and there has been some lengthy discussion, mostly centered around #369. The only solution we've documented right now is a [catch-all redirect](https://github.com/http-party/http-server#catch-all-redirect), does that work for your purposes?

As for adding a fallback option, that would be an idea for a separate project, maybe something that wraps http-server. There is a fork, [spa-http-server](https://www.npmjs.com/package/spa-http-server) which claims to provide this, and you may want to check it out.

**Comment by thornjad** [comment] 2020-01-29 14:10
Duplicate of #369

**Closed** 2020-01-29 14:10 UTC
Labels: duplicate

**Comment by Jemt** [comment] 2020-01-29 19:45
Thanks for the suggestion - the catch-all seems like a good alternative. And thanks for the effort you put into this project - it is much appreciated :-)
