### ISSUE TITLE
Serving both http/https (non-ssl/ssl)

### ISSUE THREAD

**Issue by TonyBrobston** [http-party/http-server#548] opened 2019-08-03 17:28 UTC
**Motivation / use case for feature?**
I'm needing to serve non-ssl and ssl. I'm able to serve either non-ssl or ssl but not both. Using Chrome Developer tools "Audit" which uses Lighthouse, I can test my application to see if I have regressed from 100% on performance, accessibility, best practices, seo, pwa, etc.

**Environment**
- **http-server version:** 0.11.1
- **Platform:** Vanilla html/javascript 

**Other information (related issues, suggestions for a fix, etc):**
This is the explanation from Lighthouse:
![image](https://user-images.githubusercontent.com/4724577/62415086-fee5ef00-b5e9-11e9-8e9d-5e8231fd5632.png)
In order for me to fix the redirect, I need `http-server` to serve both `http` and `https`.

This link likely won't help, but this is the repo/branch:
https://github.com/TonyBrobston/jpegasus-demo/tree/run-locally-with-ssl

**Comment by thisIsTheFoxe** [comment] 2020-01-18 00:59
check out #598

**Comment by thornjad** [comment] 2021-07-13 14:28
Duplicate of #273

**Closed by thornjad** 2021-07-13 14:28 UTC
