### ISSUE TITLE
Can't stop it with Ctrl + C [Windows only]

### ISSUE THREAD

**Issue by nicolasparada** [http-party/http-server#183] opened 2015-09-25 17:45 UTC
It's very weird. I cannot stop the server with Ctrl + C.
I'm on windows 10 with the power shell D:

**Comment by Paulooze** [comment] 2015-10-04 14:45
I have the same problem. If I hit Ctrl + C, then Enter, it looks like server has stopped, but it hasn't. Also, it seems like it's ignoring set port (server should run on port 8080, but locahost:anyport returns the page), which results in conflicts with server running on different port. 
Same OS, windows 10.

**Comment by BrianSipple** [comment] 2015-12-10 00:04
+1

**Comment by janbiasi** [comment] 2016-01-06 14:02
+1

**Comment by derhuerst** [comment] 2016-01-06 15:37
If you do `http-server -p 8888`, what does it report?

**Comment by janbiasi** [comment] 2016-01-07 10:39
```
> node node_modules/http-server/bin/http-server -o --cors -p 8888

Starting up http-server, serving ./
Available on:
  http:10.1.3.70:8888
  http:127.0.0.1:8888
Hit CTRL-C to stop the server
[Thu, 07 Jan 2016 10:37:56 GMT] "GET /" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36"
[Thu, 07 Jan 2016 10:37:56 GMT] "GET /dist/dependencies.js" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36"
[Thu, 07 Jan 2016 10:37:56 GMT] "GET /dist/application.js" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36"
[Thu, 07 Jan 2016 10:37:56 GMT] "GET /favicon.ico" "Mozilla/5.0 (Windows NT 10.0; WOW64) 
^C^C^C^C^C
```

**Comment by derhuerst** [comment] 2016-01-07 11:40
There has been a significant amount of changes since `http-server@latest`. Try `master` from GitHub and check if the issue is resolved.

**Comment by janbiasi** [comment] 2016-01-13 08:22
I've just noticed that <code>Ctrl + C</code> works on my Mac but not on windows. Hope this helps for future bugfixing. 

@derhuerst I don't want to have a NPM package working state in my project but thanks for your help :smiley:!

**Comment by derhuerst** [comment] 2016-01-13 09:17
@janbiasi why in your project? clone the repo, install dependencies and call the executable.

**Comment by janbiasi** [comment] 2016-01-13 10:14
@derhuerst because I use it as a dependecy in a project for a customer and I only use dependencies which I can maintain with a package manager. Main reason is that other collaborators will get a mess If i use NPM, Bower and direct clones from GitHub repositories. So it won't make any sense if the master would resolve the <code>Ctrl + C</code> issue :wink:

**Comment by derhuerst** [comment] 2016-01-13 10:52
@janbiasi 

> So it won't make any sense if the master would resolve the Ctrl + C issue

For two reason it would. First, npm can also load dependencies from Git repos, including tags (for releases). Second, there is a general interest in fixing bugs in this package, so it would help if cloned it somewhere and just quickly checked if the bug still appears on `master`.

**Comment by janbiasi** [comment] 2016-01-13 10:58
@derhuerst I said that I use NPM and Bower already, but I won't use the master branch in the project. Instead found another package that works pretty good. Maybe checking the master branch of this proj if I'll have enough time.

**Comment by samirop** [comment] 2016-11-11 16:16
+1 in raspbian

**Comment by derhuerst** [comment] 2016-11-11 18:46
@samirop Did you try `http-server@latest` (using npm normally) or `master`?

**Comment by Davidster** [comment] 2017-09-13 20:40
+1

**Comment by mmyrland** [comment] 2017-10-12 18:35
+1

**Comment by BigBlueHat** [comment] 2017-10-12 19:41
This issue is fairly random...and I haven't yet been able to pin down the cause (as it's not been consistently a problem). However, I do now (occasionally...) witness this on Windows 10 running Node 8.6.0 and `http-server` 0.10.0.

If any of you have more info on scenarios that cause (or prevent) this, do tell!

**Comment by TamasHuang** [comment] 2017-11-25 12:04
I'm a new guy  on React.js ,when i user serve on windows 10 , i also can't stop seve with Ctrl+c

**Comment by Pheater** [comment] 2018-09-29 18:48
+1

**Comment by dachinat** [comment] 2018-12-22 23:52
Does not work on mac

**Comment by danielcodrea** [comment] 2019-07-07 20:34
+1 have the same problem on 
windows 10
node 10.9.0

**Comment by Tokenyet** [comment] 2020-02-02 13:56
I'm not the author, but I tested for Winodws 10, that https://github.com/nbluis/static-server is working with Ctrl +C

**Comment by thornjad** [comment] 2020-02-03 20:58
For anyone who's having this issue, does CTRL+D work at all?

**Comment by evghenix** [comment] 2021-07-23 19:34
Same on:

OSX Big Sur 11.1
Node 14.15.1 
http-server 0.12.3

**Comment by thornjad** [comment] 2021-08-07 18:51
is the command you're running actually `npm run start & npm run watch` or is it `npm run start && npm run watch`?

**Comment by evghenix** [comment] 2021-09-15 16:24
@thornjad i used ```npm run start & npm run watch```

**Comment by thornjad** [comment] 2021-09-16 17:19
Since the `&` puts `npm run start` into the background, it's no longer capable of receiving CTRL+C (which only works on foreground processes); you'll have to use `kill -SIGINT` instead

**Comment by evghenix** [comment] 2021-09-16 20:33
@thornjad exactly. That was the issue in my case.

**Comment by thornjad** [comment] 2021-09-17 13:35
:tada: awesome, I'm going to close this for now since the original issue hasn't had much activity for years. Please re-open if this issue appears again

**Closed by thornjad** 2021-09-17 13:35 UTC
Labels: needs-investigation, help-wanted
