### ISSUE TITLE
http-server -p 8000 -o之后，浏览器显示该网页无法正常运作

### ISSUE THREAD

**Issue by wangdong1209** [http-party/http-server#549] opened 2019-08-07 09:52 UTC
**Do you want to request a *feature* or report a *bug*?**

**If the issue is a bug report, please provide the steps to reproduce it. Please include the actual command causing the issue if applicable.**

**What did you expect to happen?**

**What actually happened? Please include the actual error trace and / or stack trace if applicable.**

**If the issue is a feature request, what is the motivation / use case for it?**

**Tell us about your environment**
- **http-server version:**
- **Platform:**

**Other information (related issues, suggestions for a fix, etc):**

**Comment by firecloud162** [comment] 2019-08-10 22:38
试试在后面加一个此目录下存在的文件。比如说
http://localhost:8000/index.html

**Comment by thornjad** [comment] 2019-08-18 03:27
Duplicate of #525

**Closed by thornjad** 2019-08-18 03:27 UTC
